---
language: ruby
cache: bundler
sudo: required
services:
  - docker
script:
  - bundle exec rake validate lint beaker
rvm:
  - "2.4"
env:
  - BEAKER_set="default"
  - BEAKER_set="default" PUPPET_INSTALL_TYPE="agent" PUPPET_INSTALL_VERSION="1.6.2"
deploy:
  provider: puppetforge
  user: ouroboros8
  password:
    secure: "EKs+DEO68V+VvK3v0u0lRi51FiBXIJtdJN2+ZYiqaHPbSbSQAWA7NZ/QKq2WgQG+slvyM/N4e+qnMRfZL38ghHKgtKZX5Rcm1KmNTLYH6plI79DZ0MFPHAK5PqBuSXCJSLBeBjwSPup8TtogB6yYfyWnV9PosiR3aCdO3V8A1u/PWWUzEgayHxkTLgxeW/ceREwUH+HPPjfx84LULaBg3p5UJWoNONV7R8Ph+mYy2593thXPAmjLZgJEmhVyjnKn38aU8swFQQV7BKF0H3uDB8tDxrKGia+fnNQOWpTs90a4RxYPzl63GXnqRWvYZ4B9w7nhfJqlN98Wx5g88+3m4wNgRDUGhusONs3eWBiEWV/D5tFtdNUni9LPrQwKpS6XTMikaS4fFnN0FNPYtyK0p3JwaMcLa3xm1wz5zkOmlYa+BVIr3gaOs+/+HwrJtBLjKU+hB4hitk6YHbWXuohw0bWgCzAR+ZKQF0zGK3R6GnCvUfAThhxSYA5cgWr3SvPzVLjvG+xjjyBFx80Lien8uweFQk7n0gYBLS1rQ1kxEamP0DGG0XMg8JVGQIYRCyfpXv67lfvsrprLUzR6FcG9OY5awlEgnj0tCmVcUZcBg+sBH7vcJc36o9lQK8JBSF2FSPJ9vJX9q/PGdZPxilDbtNs7Bnl/WqqhLFA85+dW3LU="
  on:
    tags: true
